'''
Contains the absolute path to the database, as well as a tuple of equipment
and exercises for the exercise GUI.
'''
import os


DB_PATH = os.path.join(os.path.dirname(__file__), 'tracker.db')

EQUIPMENT = (
    'Powerblock Dumbbells',
    'Powerblock Barbell',
    'Powerblock Barbell + Fat Gripz',
    'Powerblock E-Z Curl Bar',
    'Powerblock E-Z Curl Bar + Fat Gripz',
    'Bodylastics Bands',
    'Bodyweight',
)
EXERCISES = (
    'Barbell Curls',
    'Barbell Front Raises',
    'Bar Pushdown',
    'Barbell Triceps Extension',
    'Bench Dips',
    'Bent Barbell Row',
    'Bent Dumbbell Row',
    'Bent Lateral Raise (Dumbbell)',
    'Bulgarian Split Squats',
    'Cable Crossover (High)',
    'Cable Crossover (Low)',
    'Cable Crossover (Mid)',
    'Cable Curls (Bar)',
    'Cable Upright Row',
    'Concentration Curls',
    'Decline Push-Ups',
    'Dips',
    'Dumbbell Curls (Standing)',
    'Dumbbell Curls (Standing Alternate)',
    'Dumbbell Pause Squats',
    'Dumbbell Squat',
    'Dumbbell Upright Row',
    'Flat Bench Press (Barbell)',
    'Flat Dumbbell Flyes',
    'Flat Dumbbell Press',
    'Flat Dumbbell Press (Alternate)',
    'Get-Ups',
    'Hammer Curls',
    'High Pull',
    'Incline Bench Press (Barbell)',
    'Incline Dumbbell Curls',
    'Incline Dumbbell Flye',
    'Incline Dumbbell Press',
    'Incline Dumbbell Press (Alternate)',
    'Inverted Row',
    'Low Pulley Row (Narrow)',
    'Low Pulley Row (Underhand)',
    'Low Pulley Row (Wide)',
    'One-Arm Dumbbell Lateral Raise',
    'One-Arm Dumbbell Row',
    'One-Arm Dumbbell Row (Lateral)',
    'One-Arm Low Pulley Row',
    'One-Leg Deadlift',
    'Overhead Triceps Extension (Dumbbell)',
    'Plate Front Raise',
    'Pulldown (Reverse Grip)',
    'Pulldown (Straight Arm)',
    'Pulldowns (Wide Grip)',
    'Pullovers',
    'Push-Ups',
    'Push-Ups (Close Hand)',
    'Push-Ups (Decline)',
    'Rear Delt Raise',
    'Reverse Curl',
    'Reverse Lunge',
    'Rope Curls',
    'Rope Face Pulls',
    'Rope Pushdown',
    'Seated Alternate Dumbbell Curls',
    'Seated Alternate One-Arm Dumbbell Press',
    'Seated Bent Lateral Raise',
    'Seated Lateral Raise',
    'Seated Shoulder Press',
    'Seated Shoulder Press (Alternate)',
    'Seated Triceps Extension',
    'Shrugs (Dumbbell)',
    'Standing Calf Raises',
    'Standing Front Raises',
    'Standing Lateral Raises',
    'Standing Military Press',
    'Standing Shoulder Press',
    'Step-Ups',
    'Stiff-Leg Deadlift',
    'Tate Press',
    'Triceps Extension (Lying Barbell)',
    'Triceps Extension (Lying Dumbbell)',
    'V-Bar Pushdowns',
)
