DROP TABLE IF EXISTS food;
DROP TABLE IF EXISTS week;
DROP TABLE IF EXISTS day;
DROP TABLE IF EXISTS week_day;
DROP TABLE IF EXISTS week_food;


CREATE TABLE food (id PRIMARY KEY, calories, protein) WITHOUT ROWID;
CREATE TABLE day (id PRIMARY KEY) WITHOUT ROWID;
CREATE TABLE week (id PRIMARY KEY, day_id) WITHOUT ROWID;
CREATE TABLE week_food (week_id, food_id) WITHOUT ROWID;
